app/habac_example/config/routes.rb
Rails.application.routes.draw do
  resources :auth_rules
  resources :environment_state_attributes
  resources :environment_states
  resources :operation_attributes
  resources :operations
  resources :device_attributes
  resources :devices
  resources :user_attributes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/habac_example/app/models/environment_state.rb
class EnvironmentState < ApplicationRecord
    has_many :environment_state_attributes
end

app/habac_example/app/controllers/environment_states_controller.rb
class EnvironmentStatesController < ApplicationController
  before_action :set_environment_state, only: %i[ show edit update destroy ]

  # GET /environment_states or /environment_states.json
  def index
    @environment_states = EnvironmentState.all
  end

  # GET /environment_states/1 or /environment_states/1.json
  def show
  end

  # GET /environment_states/new
  def new
    @environment_state = EnvironmentState.new
  end

  # GET /environment_states/1/edit
  def edit
  end

  # POST /environment_states or /environment_states.json
  def create
    @environment_state = EnvironmentState.new(environment_state_params)

    respond_to do |format|
      if @environment_state.save
        format.html { redirect_to environment_state_url(@environment_state), notice: "Environment state was successfully created." }
        format.json { render :show, status: :created, location: @environment_state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @environment_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /environment_states/1 or /environment_states/1.json
  def update
    respond_to do |format|
      if @environment_state.update(environment_state_params)
        format.html { redirect_to environment_state_url(@environment_state), notice: "Environment state was successfully updated." }
        format.json { render :show, status: :ok, location: @environment_state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @environment_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /environment_states/1 or /environment_states/1.json
  def destroy
    @environment_state.destroy

    respond_to do |format|
      format.html { redirect_to environment_states_url, notice: "Environment state was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_environment_state
      @environment_state = EnvironmentState.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def environment_state_params
      params.require(:environment_state).permit(:name)
    end
end

app/habac_example/app/helpers/environment_states_helper.rb
module EnvironmentStatesHelper
end

app/habac_example/app/views/environment_states/_environment_state.html.erb
<div id="<%= dom_id environment_state %>">
  <p>
    <strong>Name:</strong>
    <%= environment_state.name %>
  </p>

</div>

app/habac_example/app/views/environment_states/_form.html.erb
<%= form_with(model: environment_state) do |form| %>
  <% if environment_state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(environment_state.errors.count, "error") %> prohibited this environment_state from being saved:</h2>

      <ul>
        <% environment_state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/habac_example/app/views/environment_states/edit.html.erb
<h1>Editing environment state</h1>

<%= render "form", environment_state: @environment_state %>

<br>

<div>
  <%= link_to "Show this environment state", @environment_state %> |
  <%= link_to "Back to environment states", environment_states_path %>
</div>

app/habac_example/app/views/environment_states/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Environment states</h1>

<div id="environment_states">
  <% @environment_states.each do |environment_state| %>
    <%= render environment_state %>
    <p>
      <%= link_to "Show this environment state", environment_state %>
    </p>
  <% end %>
</div>

<%= link_to "New environment state", new_environment_state_path %>

app/habac_example/app/views/environment_states/new.html.erb
<h1>New environment state</h1>

<%= render "form", environment_state: @environment_state %>

<br>

<div>
  <%= link_to "Back to environment states", environment_states_path %>
</div>

app/habac_example/app/views/environment_states/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @environment_state %>

<div>
  <%= link_to "Edit this environment state", edit_environment_state_path(@environment_state) %> |
  <%= link_to "Back to environment states", environment_states_path %>

  <%= button_to "Destroy this environment state", @environment_state, method: :delete %>
</div>