app/habac_example/config/routes.rb
Rails.application.routes.draw do
  resources :auth_rules
  resources :environment_state_attributes
  resources :environment_states
  resources :operation_attributes
  resources :operations
  resources :device_attributes
  resources :devices
  resources :user_attributes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/habac_example/app/models/user_attribute.rb
class UserAttribute < ApplicationRecord
  belongs_to :user
end

app/habac_example/app/controllers/user_attributes_controller.rb
class UserAttributesController < ApplicationController
  before_action :set_user_attribute, only: %i[ show edit update destroy ]

  # GET /user_attributes or /user_attributes.json
  def index
    @user_attributes = UserAttribute.all
  end

  # GET /user_attributes/1 or /user_attributes/1.json
  def show
  end

  # GET /user_attributes/new
  def new
    @user_attribute = UserAttribute.new
  end

  # GET /user_attributes/1/edit
  def edit
  end

  # POST /user_attributes or /user_attributes.json
  def create
    @user_attribute = UserAttribute.new(user_attribute_params)

    respond_to do |format|
      if @user_attribute.save
        format.html { redirect_to user_attribute_url(@user_attribute), notice: "User attribute was successfully created." }
        format.json { render :show, status: :created, location: @user_attribute }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_attributes/1 or /user_attributes/1.json
  def update
    respond_to do |format|
      if @user_attribute.update(user_attribute_params)
        format.html { redirect_to user_attribute_url(@user_attribute), notice: "User attribute was successfully updated." }
        format.json { render :show, status: :ok, location: @user_attribute }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_attributes/1 or /user_attributes/1.json
  def destroy
    @user_attribute.destroy

    respond_to do |format|
      format.html { redirect_to user_attributes_url, notice: "User attribute was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_attribute
      @user_attribute = UserAttribute.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_attribute_params
      params.require(:user_attribute).permit(:user_id, :name, :values)
    end
end

app/habac_example/app/helpers/user_attributes_helper.rb
module UserAttributesHelper
end

app/habac_example/app/views/user_attributes/_form.html.erb
<%= form_with(model: user_attribute) do |form| %>
  <% if user_attribute.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_attribute.errors.count, "error") %> prohibited this user_attribute from being saved:</h2>

      <ul>
        <% user_attribute.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.select :user_id,  options_for_select(User.all.map{|s|[s.email, s.id]}) %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :values %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/habac_example/app/views/user_attributes/_user_attribute.html.erb
<div id="<%= dom_id user_attribute %>">
  <p>
    <strong>User:</strong>
    <%= user_attribute.user_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user_attribute.name %>
  </p>

  <p>
    <strong>Values:</strong>
    <%= user_attribute.values %>
  </p>

</div>

app/habac_example/app/views/user_attributes/edit.html.erb
<h1>Editing user attribute</h1>

<%= render "form", user_attribute: @user_attribute %>

<br>

<div>
  <%= link_to "Show this user attribute", @user_attribute %> |
  <%= link_to "Back to user attributes", user_attributes_path %>
</div>

app/habac_example/app/views/user_attributes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User attributes</h1>

<div id="user_attributes">
  <% @user_attributes.each do |user_attribute| %>
    <%= render user_attribute %>
    <p>
      <%= link_to "Show this user attribute", user_attribute %>
    </p>
  <% end %>
</div>

<%= link_to "New user attribute", new_user_attribute_path %>

app/habac_example/app/views/user_attributes/new.html.erb
<h1>New user attribute</h1>

<%= render "form", user_attribute: @user_attribute %>

<br>

<div>
  <%= link_to "Back to user attributes", user_attributes_path %>
</div>

app/habac_example/app/views/user_attributes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_attribute %>

<div>
  <%= link_to "Edit this user attribute", edit_user_attribute_path(@user_attribute) %> |
  <%= link_to "Back to user attributes", user_attributes_path %>

  <%= button_to "Destroy this user attribute", @user_attribute, method: :delete %>
</div>