app/habac_example/config/routes.rb
Rails.application.routes.draw do
  resources :auth_rules
  resources :environment_state_attributes
  resources :environment_states
  resources :operation_attributes
  resources :operations
  resources :device_attributes
  resources :devices
  resources :user_attributes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/habac_example/app/models/device_attribute.rb
class DeviceAttribute < ApplicationRecord
  belongs_to :device
end

app/habac_example/app/controllers/device_attributes_controller.rb
class DeviceAttributesController < ApplicationController
  before_action :set_device_attribute, only: %i[ show edit update destroy ]

  # GET /device_attributes or /device_attributes.json
  def index
    @device_attributes = DeviceAttribute.all
  end

  # GET /device_attributes/1 or /device_attributes/1.json
  def show
  end

  # GET /device_attributes/new
  def new
    @device_attribute = DeviceAttribute.new
  end

  # GET /device_attributes/1/edit
  def edit
  end

  # POST /device_attributes or /device_attributes.json
  def create
    @device_attribute = DeviceAttribute.new(device_attribute_params)

    respond_to do |format|
      if @device_attribute.save
        format.html { redirect_to device_attribute_url(@device_attribute), notice: "Device attribute was successfully created." }
        format.json { render :show, status: :created, location: @device_attribute }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @device_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_attributes/1 or /device_attributes/1.json
  def update
    respond_to do |format|
      if @device_attribute.update(device_attribute_params)
        format.html { redirect_to device_attribute_url(@device_attribute), notice: "Device attribute was successfully updated." }
        format.json { render :show, status: :ok, location: @device_attribute }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @device_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_attributes/1 or /device_attributes/1.json
  def destroy
    @device_attribute.destroy

    respond_to do |format|
      format.html { redirect_to device_attributes_url, notice: "Device attribute was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_attribute
      @device_attribute = DeviceAttribute.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def device_attribute_params
      params.require(:device_attribute).permit(:name, :values, :device_id)
    end
end

app/habac_example/app/helpers/device_attributes_helper.rb
module DeviceAttributesHelper
end

app/habac_example/app/views/device_attributes/_device_attribute.html.erb
<div id="<%= dom_id device_attribute %>">
  <p>
    <strong>Name:</strong>
    <%= device_attribute.name %>
  </p>

  <p>
    <strong>Values:</strong>
    <%= device_attribute.values %>
  </p>

  <p>
    <strong>Device:</strong>
    <%= device_attribute.device_id %>
  </p>

</div>

app/habac_example/app/views/device_attributes/_form.html.erb
<%= form_with(model: device_attribute) do |form| %>
  <% if device_attribute.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(device_attribute.errors.count, "error") %> prohibited this device_attribute from being saved:</h2>

      <ul>
        <% device_attribute.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :values, style: "display: block" %>
    <%= form.text_field :values %>
  </div>

  <div>
    <%= form.label :device_id, style: "display: block" %>
    <%= form.select :device_id, options_for_select(Device.all.map{|s|[s.name, s.id]}) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/habac_example/app/views/device_attributes/edit.html.erb
<h1>Editing device attribute</h1>

<%= render "form", device_attribute: @device_attribute %>

<br>

<div>
  <%= link_to "Show this device attribute", @device_attribute %> |
  <%= link_to "Back to device attributes", device_attributes_path %>
</div>

app/habac_example/app/views/device_attributes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Device attributes</h1>

<div id="device_attributes">
  <% @device_attributes.each do |device_attribute| %>
    <%= render device_attribute %>
    <p>
      <%= link_to "Show this device attribute", device_attribute %>
    </p>
  <% end %>
</div>

<%= link_to "New device attribute", new_device_attribute_path %>

app/habac_example/app/views/device_attributes/new.html.erb
<h1>New device attribute</h1>

<%= render "form", device_attribute: @device_attribute %>

<br>

<div>
  <%= link_to "Back to device attributes", device_attributes_path %>
</div>

app/habac_example/app/views/device_attributes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @device_attribute %>

<div>
  <%= link_to "Edit this device attribute", edit_device_attribute_path(@device_attribute) %> |
  <%= link_to "Back to device attributes", device_attributes_path %>

  <%= button_to "Destroy this device attribute", @device_attribute, method: :delete %>
</div>